### ISSUE TITLE
[BUG][CRITICAL] Cannot access internal storage - Android 10+

### ISSUE THREAD

**Issue by yukosky** [goldxn/quod-explorer#6]
When the application is opened, it freeze on the startup screen, soon I will compile it on my own and take logs.
@goldxn

**Comment by goldxn** [comment]
Okay

**Comment by goldxn** [comment]
Please send me logs (error messages), otherwise I can't help.

**Comment by goldxn** [comment]
This issue is closed because of lacking of information. Send device info and logs because I can't confirm it. Try to use quod's new version

**Comment by goldxn** [comment]
Confirmed by myself. Android 10 - Samsung A30s

**Comment by goldxn** [comment]
Temporary fix https://github.com/goldxn/quod-explorer/commit/472f54cb79924c7593ff4bf17d1bbcd0182fa7c7
